name: Build and Publish LaTeX document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        latex_file:
          - aud
          - thinf
          - db
          - sosy
          - ddi

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.latex_file }}.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.latex_file }}-pdf
          path: ${{ matrix.latex_file }}.pdf

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
